# Generated by Django 2.1.2 on 2018-10-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('colname_en', models.CharField(max_length=150)),
                ('colname_fr', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('colname_en', models.CharField(max_length=150)),
                ('colname_fr', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=32)),
                ('orgname_en', models.CharField(max_length=150)),
                ('orgname_fr', models.CharField(max_length=150)),
            ],
        ),
    ]
