# Generated by Django 2.1.5 on 2019-01-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=2)),
                ('action', models.CharField(max_length=12)),
                ('timestamp', models.TimeField()),
                ('search_terms', models.CharField(max_length=150)),
                ('organization_terms', models.CharField(max_length=256)),
                ('portal_terms', models.CharField(max_length=128)),
                ('jurisdiction_terms', models.CharField(max_length=128)),
                ('collection_terms', models.CharField(max_length=256)),
                ('keyword_terms', models.CharField(max_length=256)),
                ('subject_terms', models.CharField(max_length=256)),
                ('format_terms', models.CharField(max_length=256)),
                ('res_type_terms', models.CharField(max_length=256)),
                ('frequency_terms', models.CharField(max_length=256)),
            ],
        ),
    ]
